services:
    devcontainer:
        image: mcr.microsoft.com/devcontainers/dotnet:10.0
        volumes:
          - ..:/workspace:cached
        command: sleep infinity
    redis:
        image: redis